export const columns4 = ["Manufacturer","Model Name","Category","Screen Size","Screen","CPU","RAM","Storage","GPU","Operating System","Operating System Version","Weight","Price"];
export const data4 = [
    {
      "Manufacturer": "Apple",
      "Model Name": "MacBook Pro",
      "Category": "Ultrabook",
      "Screen Size": 13.3,
      "Screen": "IPS Panel Retina Display 2560x1600",
      "CPU": "Intel Core i5 2.3GHz",
      "RAM": "8GB",
      "Storage": "128GB SSD",
      "GPU": "Intel Iris Plus Graphics 640",
      "Operating System": "macOS",
      "Operating System Version": "",
      "Weight": "1.37kg",
      "Price": 11912523.48
    },
    {
      "Manufacturer": "Apple",
      "Model Name": "Macbook Air",
      "Category": "Ultrabook",
      "Screen Size": 13.3,
      "Screen": "1440x900",
      "CPU": "Intel Core i5 1.8GHz",
      "RAM": "8GB",
      "Storage": "128GB Flash Storage",
      "GPU": "Intel HD Graphics 6000",
      "Operating System": "macOS",
      "Operating System Version": "",
      "Weight": "1.34kg",
      "Price": 7993374.48
    },
    {
      "Manufacturer": "HP",
      "Model Name": "250 G6",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "Full HD 1920x1080",
      "CPU": "Intel Core i5 7200U 2.5GHz",
      "RAM": "8GB",
      "Storage": "256GB SSD",
      "GPU": "Intel HD Graphics 620",
      "Operating System": "No OS",
      "Operating System Version": "",
      "Weight": "1.86kg",
      "Price": 5112900
    },
    {
      "Manufacturer": "Apple",
      "Model Name": "MacBook Pro",
      "Category": "Ultrabook",
      "Screen Size": 15.4,
      "Screen": "IPS Panel Retina Display 2880x1800",
      "CPU": "Intel Core i7 2.7GHz",
      "RAM": "16GB",
      "Storage": "512GB SSD",
      "GPU": "AMD Radeon Pro 455",
      "Operating System": "macOS",
      "Operating System Version": "",
      "Weight": "1.83kg",
      "Price": 22563005.4
    },
    {
      "Manufacturer": "Apple",
      "Model Name": "MacBook Pro",
      "Category": "Ultrabook",
      "Screen Size": 13.3,
      "Screen": "IPS Panel Retina Display 2560x1600",
      "CPU": "Intel Core i5 3.1GHz",
      "RAM": "8GB",
      "Storage": "256GB SSD",
      "GPU": "Intel Iris Plus Graphics 650",
      "Operating System": "macOS",
      "Operating System Version": "",
      "Weight": "1.37kg",
      "Price": 16037611.2
    },
    {
      "Manufacturer": "Acer",
      "Model Name": "Aspire 3",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "1366x768",
      "CPU": "AMD A9-Series 9420 3GHz",
      "RAM": "4GB",
      "Storage": "500GB HDD",
      "GPU": "AMD Radeon R5",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "2.1kg",
      "Price": 3556800
    },
    {
      "Manufacturer": "Apple",
      "Model Name": "MacBook Pro",
      "Category": "Ultrabook",
      "Screen Size": 15.4,
      "Screen": "IPS Panel Retina Display 2880x1800",
      "CPU": "Intel Core i7 2.2GHz",
      "RAM": "16GB",
      "Storage": "256GB Flash Storage",
      "GPU": "Intel Iris Pro Graphics",
      "Operating System": "Mac OS",
      "Operating System Version": "X",
      "Weight": "2.04kg",
      "Price": 19028613.24
    },
    {
      "Manufacturer": "Apple",
      "Model Name": "Macbook Air",
      "Category": "Ultrabook",
      "Screen Size": 13.3,
      "Screen": "1440x900",
      "CPU": "Intel Core i5 1.8GHz",
      "RAM": "8GB",
      "Storage": "256GB Flash Storage",
      "GPU": "Intel HD Graphics 6000",
      "Operating System": "macOS",
      "Operating System Version": "",
      "Weight": "1.34kg",
      "Price": 10303160.4
    },
    {
      "Manufacturer": "Asus",
      "Model Name": "ZenBook UX430UN",
      "Category": "Ultrabook",
      "Screen Size": 14,
      "Screen": "Full HD 1920x1080",
      "CPU": "Intel Core i7 8550U 1.8GHz",
      "RAM": "16GB",
      "Storage": "512GB SSD",
      "GPU": "Nvidia GeForce MX150",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "1.3kg",
      "Price": 13293540
    },
    {
      "Manufacturer": "Acer",
      "Model Name": "Swift 3",
      "Category": "Ultrabook",
      "Screen Size": 14,
      "Screen": "IPS Panel Full HD 1920x1080",
      "CPU": "Intel Core i5 8250U 1.6GHz",
      "RAM": "8GB",
      "Storage": "256GB SSD",
      "GPU": "Intel UHD Graphics 620",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "1.6kg",
      "Price": 6846840
    },
    {
      "Manufacturer": "HP",
      "Model Name": "250 G6",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "1366x768",
      "CPU": "Intel Core i5 7200U 2.5GHz",
      "RAM": "4GB",
      "Storage": "500GB HDD",
      "GPU": "Intel HD Graphics 620",
      "Operating System": "No OS",
      "Operating System Version": "",
      "Weight": "1.86kg",
      "Price": 3502558.8
    },
    {
      "Manufacturer": "HP",
      "Model Name": "250 G6",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "Full HD 1920x1080",
      "CPU": "Intel Core i3 6006U 2GHz",
      "RAM": "4GB",
      "Storage": "500GB HDD",
      "GPU": "Intel HD Graphics 520",
      "Operating System": "No OS",
      "Operating System Version": "",
      "Weight": "1.86kg",
      "Price": 3067651.08
    },
    {
      "Manufacturer": "Apple",
      "Model Name": "MacBook Pro",
      "Category": "Ultrabook",
      "Screen Size": 15.4,
      "Screen": "IPS Panel Retina Display 2880x1800",
      "CPU": "Intel Core i7 2.8GHz",
      "RAM": "16GB",
      "Storage": "256GB SSD",
      "GPU": "AMD Radeon Pro 555",
      "Operating System": "macOS",
      "Operating System Version": "",
      "Weight": "1.83kg",
      "Price": 21696213.24
    },
    {
      "Manufacturer": "Dell",
      "Model Name": "Inspiron 3567",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "Full HD 1920x1080",
      "CPU": "Intel Core i3 6006U 2GHz",
      "RAM": "4GB",
      "Storage": "256GB SSD",
      "GPU": "AMD Radeon R5 M430",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "2.2kg",
      "Price": 4436218.8
    },
    {
      "Manufacturer": "Apple",
      "Model Name": "MacBook 12",
      "Category": "Ultrabook",
      "Screen Size": 12,
      "Screen": "IPS Panel Retina Display 2304x1440",
      "CPU": "Intel Core M m3 1.2GHz",
      "RAM": "8GB",
      "Storage": "256GB SSD",
      "GPU": "Intel HD Graphics 615",
      "Operating System": "macOS",
      "Operating System Version": "",
      "Weight": "0.92kg",
      "Price": 11225260.8
    },
    {
      "Manufacturer": "Apple",
      "Model Name": "MacBook Pro",
      "Category": "Ultrabook",
      "Screen Size": 13.3,
      "Screen": "IPS Panel Retina Display 2560x1600",
      "CPU": "Intel Core i5 2.3GHz",
      "RAM": "8GB",
      "Storage": "256GB SSD",
      "GPU": "Intel Iris Plus Graphics 640",
      "Operating System": "macOS",
      "Operating System Version": "",
      "Weight": "1.37kg",
      "Price": 13502946.6
    },
    {
      "Manufacturer": "Dell",
      "Model Name": "Inspiron 3567",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "Full HD 1920x1080",
      "CPU": "Intel Core i7 7500U 2.7GHz",
      "RAM": "8GB",
      "Storage": "256GB SSD",
      "GPU": "AMD Radeon R5 M430",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "2.2kg",
      "Price": 6624540
    },
    {
      "Manufacturer": "Apple",
      "Model Name": "MacBook Pro",
      "Category": "Ultrabook",
      "Screen Size": 15.4,
      "Screen": "IPS Panel Retina Display 2880x1800",
      "CPU": "Intel Core i7 2.9GHz",
      "RAM": "16GB",
      "Storage": "512GB SSD",
      "GPU": "AMD Radeon Pro 560",
      "Operating System": "macOS",
      "Operating System Version": "",
      "Weight": "1.83kg",
      "Price": 25413336
    },
    {
      "Manufacturer": "Lenovo",
      "Model Name": "IdeaPad 320-15IKB",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "Full HD 1920x1080",
      "CPU": "Intel Core i3 7100U 2.4GHz",
      "RAM": "8GB",
      "Storage": "1TB HDD",
      "GPU": "Nvidia GeForce 940MX",
      "Operating System": "No OS",
      "Operating System Version": "",
      "Weight": "2.2kg",
      "Price": 4437108
    },
    {
      "Manufacturer": "Dell",
      "Model Name": "XPS 13",
      "Category": "Ultrabook",
      "Screen Size": 13.3,
      "Screen": "IPS Panel Full HD / Touchscreen 1920x1080",
      "CPU": "Intel Core i5 8250U 1.6GHz",
      "RAM": "8GB",
      "Storage": "128GB SSD",
      "GPU": "Intel UHD Graphics 620",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "1.22kg",
      "Price": 8705268
    },
    {
      "Manufacturer": "Asus",
      "Model Name": "Vivobook E200HA",
      "Category": "Netbook",
      "Screen Size": 11.6,
      "Screen": "1366x768",
      "CPU": "Intel Atom x5-Z8350 1.44GHz",
      "RAM": "2GB",
      "Storage": "32GB Flash Storage",
      "GPU": "Intel HD Graphics 400",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "0.98kg",
      "Price": 1706374.8
    },
    {
      "Manufacturer": "Lenovo",
      "Model Name": "Legion Y520-15IKBN",
      "Category": "Gaming",
      "Screen Size": 15.6,
      "Screen": "IPS Panel Full HD 1920x1080",
      "CPU": "Intel Core i5 7300HQ 2.5GHz",
      "RAM": "8GB",
      "Storage": "128GB SSD +  1TB HDD",
      "GPU": "Nvidia GeForce GTX 1050",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "2.5kg",
      "Price": 8883108
    },
    {
      "Manufacturer": "HP",
      "Model Name": "255 G6",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "1366x768",
      "CPU": "AMD E-Series E2-9000e 1.5GHz",
      "RAM": "4GB",
      "Storage": "500GB HDD",
      "GPU": "AMD Radeon R2",
      "Operating System": "No OS",
      "Operating System Version": "",
      "Weight": "1.86kg",
      "Price": 2294136
    },
    {
      "Manufacturer": "Dell",
      "Model Name": "Inspiron 5379",
      "Category": "2 in 1 Convertible",
      "Screen Size": 13.3,
      "Screen": "Full HD / Touchscreen 1920x1080",
      "CPU": "Intel Core i5 8250U 1.6GHz",
      "RAM": "8GB",
      "Storage": "256GB SSD",
      "GPU": "Intel UHD Graphics 620",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "1.62kg",
      "Price": 7282548
    },
    {
      "Manufacturer": "HP",
      "Model Name": "15-BS101nv (i7-8550U/8GB/256GB/FHD/W10)",
      "Category": "Ultrabook",
      "Screen Size": 15.6,
      "Screen": "Full HD 1920x1080",
      "CPU": "Intel Core i7 8550U 1.8GHz",
      "RAM": "8GB",
      "Storage": "256GB SSD",
      "GPU": "Intel HD Graphics 620",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "1.91kg",
      "Price": 5859828
    },
    {
      "Manufacturer": "Dell",
      "Model Name": "Inspiron 3567",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "1366x768",
      "CPU": "Intel Core i3 6006U 2GHz",
      "RAM": "4GB",
      "Storage": "1TB HDD",
      "GPU": "Intel HD Graphics 520",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "2.3kg",
      "Price": 3722546.88
    },
    {
      "Manufacturer": "Apple",
      "Model Name": "MacBook Air",
      "Category": "Ultrabook",
      "Screen Size": 13.3,
      "Screen": "1440x900",
      "CPU": "Intel Core i5 1.6GHz",
      "RAM": "8GB",
      "Storage": "128GB Flash Storage",
      "GPU": "Intel HD Graphics 6000",
      "Operating System": "Mac OS",
      "Operating System Version": "X",
      "Weight": "1.35kg",
      "Price": 9772308
    },
    {
      "Manufacturer": "Dell",
      "Model Name": "Inspiron 5570",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "Full HD 1920x1080",
      "CPU": "Intel Core i5 8250U 1.6GHz",
      "RAM": "8GB",
      "Storage": "256GB SSD",
      "GPU": "AMD Radeon 530",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "2.2kg",
      "Price": 7113600
    },
    {
      "Manufacturer": "Dell",
      "Model Name": "Latitude 5590",
      "Category": "Ultrabook",
      "Screen Size": 15.6,
      "Screen": "Full HD 1920x1080",
      "CPU": "Intel Core i7 8650U 1.9GHz",
      "RAM": "8GB",
      "Storage": "256GB SSD +  256GB SSD",
      "GPU": "Intel UHD Graphics 620",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "1.88kg",
      "Price": 11541816
    },
    {
      "Manufacturer": "HP",
      "Model Name": "ProBook 470",
      "Category": "Notebook",
      "Screen Size": 17.3,
      "Screen": "Full HD 1920x1080",
      "CPU": "Intel Core i5 8250U 1.6GHz",
      "RAM": "8GB",
      "Storage": "1TB HDD",
      "GPU": "Nvidia GeForce 930MX",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "2.5kg",
      "Price": 7967232
    },
    {
      "Manufacturer": "Chuwi",
      "Model Name": "LapBook 15.6",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "Full HD 1920x1080",
      "CPU": "Intel Atom x5-Z8300 1.44GHz",
      "RAM": "4GB",
      "Storage": "64GB Flash Storage",
      "GPU": "Intel HD Graphics",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "1.89kg",
      "Price": 2178451.08
    },
    {
      "Manufacturer": "Asus",
      "Model Name": "E402WA-GA010T (E2-6110/2GB/32GB/W10)",
      "Category": "Notebook",
      "Screen Size": 14,
      "Screen": "1366x768",
      "CPU": "AMD E-Series E2-6110 1.5GHz",
      "RAM": "2GB",
      "Storage": "32GB Flash Storage",
      "GPU": "AMD Radeon R2",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "1.65kg",
      "Price": 1769508
    },
    {
      "Manufacturer": "HP",
      "Model Name": "17-ak001nv (A6-9220/4GB/500GB/Radeon",
      "Category": "Notebook",
      "Screen Size": 17.3,
      "Screen": "Full HD 1920x1080",
      "CPU": "AMD A6-Series 9220 2.5GHz",
      "RAM": "4GB",
      "Storage": "500GB HDD",
      "GPU": "AMD Radeon 530",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "2.71kg",
      "Price": 3903588
    },
    {
      "Manufacturer": "Dell",
      "Model Name": "XPS 13",
      "Category": "Ultrabook",
      "Screen Size": 13.3,
      "Screen": "Touchscreen / Quad HD+ 3200x1800",
      "CPU": "Intel Core i7 8550U 1.8GHz",
      "RAM": "16GB",
      "Storage": "512GB SSD",
      "GPU": "Intel UHD Graphics 620",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "1.2kg",
      "Price": 16619148
    },
    {
      "Manufacturer": "Apple",
      "Model Name": "MacBook Air",
      "Category": "Ultrabook",
      "Screen Size": 13.3,
      "Screen": "1440x900",
      "CPU": "Intel Core i5 1.6GHz",
      "RAM": "8GB",
      "Storage": "256GB Flash Storage",
      "GPU": "Intel HD Graphics 6000",
      "Operating System": "Mac OS",
      "Operating System Version": "X",
      "Weight": "1.35kg",
      "Price": 8874216
    },
    {
      "Manufacturer": "Lenovo",
      "Model Name": "IdeaPad 120S-14IAP",
      "Category": "Notebook",
      "Screen Size": 14,
      "Screen": "1366x768",
      "CPU": "Intel Celeron Dual Core N3350 1.1GHz",
      "RAM": "4GB",
      "Storage": "64GB Flash Storage",
      "GPU": "Intel HD Graphics 500",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "1.44kg",
      "Price": 2214108
    },
    {
      "Manufacturer": "Acer",
      "Model Name": "Aspire 3",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "1366x768",
      "CPU": "Intel Core i3 7130U 2.7GHz",
      "RAM": "4GB",
      "Storage": "1TB HDD",
      "GPU": "Intel HD Graphics 620",
      "Operating System": "Linux",
      "Operating System Version": "",
      "Weight": "2.1kg",
      "Price": 3263364
    },
    {
      "Manufacturer": "Dell",
      "Model Name": "Inspiron 5770",
      "Category": "Notebook",
      "Screen Size": 17.3,
      "Screen": "IPS Panel Full HD 1920x1080",
      "CPU": "Intel Core i5 8250U 1.6GHz",
      "RAM": "8GB",
      "Storage": "128GB SSD +  1TB HDD",
      "GPU": "AMD Radeon 530",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "2.8kg",
      "Price": 8705268
    },
    {
      "Manufacturer": "HP",
      "Model Name": "250 G6",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "1366x768",
      "CPU": "Intel Core i5 7200U 2.5GHz",
      "RAM": "4GB",
      "Storage": "1TB HDD",
      "GPU": "Intel HD Graphics 620",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "1.86kg",
      "Price": 4345431.48
    },
    {
      "Manufacturer": "HP",
      "Model Name": "ProBook 450",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "Full HD 1920x1080",
      "CPU": "Intel Core i5 8250U 1.6GHz",
      "RAM": "8GB",
      "Storage": "256GB SSD",
      "GPU": "Nvidia GeForce 930MX",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "2.1kg",
      "Price": 7816068
    },
    {
      "Manufacturer": "Asus",
      "Model Name": "X540UA-DM186 (i3-6006U/4GB/1TB/FHD/Linux)",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "Full HD 1920x1080",
      "CPU": "Intel Core i3 6006U 2GHz",
      "RAM": "4GB",
      "Storage": "1TB HDD",
      "GPU": "Intel HD Graphics 620",
      "Operating System": "Linux",
      "Operating System Version": "",
      "Weight": "2kg",
      "Price": 3458988
    },
    {
      "Manufacturer": "Dell",
      "Model Name": "Inspiron 7577",
      "Category": "Gaming",
      "Screen Size": 15.6,
      "Screen": "IPS Panel Full HD 1920x1080",
      "CPU": "Intel Core i7 7700HQ 2.8GHz",
      "RAM": "16GB",
      "Storage": "256GB SSD +  1TB HDD",
      "GPU": "Nvidia GeForce GTX 1060",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "2.65kg",
      "Price": 13329108
    },
    {
      "Manufacturer": "Asus",
      "Model Name": "X542UQ-GO005 (i5-7200U/8GB/1TB/GeForce",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "1366x768",
      "CPU": "Intel Core i5 7200U 2.5GHz",
      "RAM": "8GB",
      "Storage": "1TB HDD",
      "GPU": "Nvidia GeForce 940MX",
      "Operating System": "Linux",
      "Operating System Version": "",
      "Weight": "2.3kg",
      "Price": 4650427.08
    },
    {
      "Manufacturer": "Acer",
      "Model Name": "Aspire A515-51G",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "IPS Panel Full HD 1920x1080",
      "CPU": "Intel Core i5 8250U 1.6GHz",
      "RAM": "4GB",
      "Storage": "256GB SSD",
      "GPU": "Intel UHD Graphics 620",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "2.2kg",
      "Price": 6064344
    },
    {
      "Manufacturer": "Dell",
      "Model Name": "Inspiron 7773",
      "Category": "2 in 1 Convertible",
      "Screen Size": 17.3,
      "Screen": "Full HD / Touchscreen 1920x1080",
      "CPU": "Intel Core i5 8250U 1.6GHz",
      "RAM": "12GB",
      "Storage": "1TB HDD",
      "GPU": "Nvidia GeForce 150MX",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "2.77kg",
      "Price": 8883108
    },
    {
      "Manufacturer": "Apple",
      "Model Name": "MacBook Pro",
      "Category": "Ultrabook",
      "Screen Size": 13.3,
      "Screen": "IPS Panel Retina Display 2560x1600",
      "CPU": "Intel Core i5 2.0GHz",
      "RAM": "8GB",
      "Storage": "256GB SSD",
      "GPU": "Intel Iris Graphics 540",
      "Operating System": "macOS",
      "Operating System Version": "",
      "Weight": "1.37kg",
      "Price": 12617748
    },
    {
      "Manufacturer": "Lenovo",
      "Model Name": "IdeaPad 320-15ISK",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "1366x768",
      "CPU": "Intel Core i3 6006U 2GHz",
      "RAM": "4GB",
      "Storage": "128GB SSD",
      "GPU": "Intel HD Graphics 520",
      "Operating System": "No OS",
      "Operating System Version": "",
      "Weight": "2.2kg",
      "Price": 3281148
    },
    {
      "Manufacturer": "Asus",
      "Model Name": "Rog Strix",
      "Category": "Gaming",
      "Screen Size": 17.3,
      "Screen": "Full HD 1920x1080",
      "CPU": "AMD Ryzen 1700 3GHz",
      "RAM": "8GB",
      "Storage": "256GB SSD +  1TB HDD",
      "GPU": "AMD Radeon RX 580",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "3.2kg",
      "Price": 11550708
    },
    {
      "Manufacturer": "Dell",
      "Model Name": "Inspiron 3567",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "Full HD 1920x1080",
      "CPU": "Intel Core i5 7200U 2.5GHz",
      "RAM": "4GB",
      "Storage": "256GB SSD",
      "GPU": "AMD Radeon R5 M430",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "2.3kg",
      "Price": 5681988
    },
    {
      "Manufacturer": "Asus",
      "Model Name": "X751NV-TY001T (N4200/4GB/1TB/GeForce",
      "Category": "Notebook",
      "Screen Size": 17.3,
      "Screen": "1366x768",
      "CPU": "Intel Pentium Quad Core N4200 1.1GHz",
      "RAM": "4GB",
      "Storage": "1TB HDD",
      "GPU": "Nvidia GeForce 920MX",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "2.8kg",
      "Price": 4143672
    },
    {
      "Manufacturer": "Lenovo",
      "Model Name": "Yoga Book",
      "Category": "2 in 1 Convertible",
      "Screen Size": 10.1,
      "Screen": "IPS Panel Touchscreen 1920x1200",
      "CPU": "Intel Atom x5-Z8550 1.44GHz",
      "RAM": "4GB",
      "Storage": "64GB Flash Storage",
      "GPU": "Intel HD Graphics 400",
      "Operating System": "Android",
      "Operating System Version": "",
      "Weight": "0.69kg",
      "Price": 2836548
    },
    {
      "Manufacturer": "Acer",
      "Model Name": "Aspire A515-51G",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "IPS Panel Full HD 1920x1080",
      "CPU": "Intel Core i7 8550U 1.8GHz",
      "RAM": "8GB",
      "Storage": "256GB SSD",
      "GPU": "Nvidia GeForce MX150",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "2.2kg",
      "Price": 7478172
    },
    {
      "Manufacturer": "HP",
      "Model Name": "255 G6",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "Full HD 1920x1080",
      "CPU": "AMD A6-Series 9220 2.5GHz",
      "RAM": "4GB",
      "Storage": "256GB SSD",
      "GPU": "AMD Radeon R4 Graphics",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "1.86kg",
      "Price": 3543373.08
    },
    {
      "Manufacturer": "HP",
      "Model Name": "ProBook 430",
      "Category": "Notebook",
      "Screen Size": 13.3,
      "Screen": "Full HD 1920x1080",
      "CPU": "Intel Core i7 8550U 1.8GHz",
      "RAM": "8GB",
      "Storage": "512GB SSD",
      "GPU": "Intel UHD Graphics 620",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "1.49kg",
      "Price": 9807876
    },
    {
      "Manufacturer": "Acer",
      "Model Name": "Aspire 3",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "1366x768",
      "CPU": "Intel Core i3 7100U 2.4GHz",
      "RAM": "4GB",
      "Storage": "1TB HDD",
      "GPU": "Intel HD Graphics 620",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "2.4kg",
      "Price": 3414528
    },
    {
      "Manufacturer": "Dell",
      "Model Name": "Inspiron 3576",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "Full HD 1920x1080",
      "CPU": "Intel Core i7 8550U 1.8GHz",
      "RAM": "8GB",
      "Storage": "256GB SSD",
      "GPU": "AMD Radeon 520",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "2.13kg",
      "Price": 6827277.6
    },
    {
      "Manufacturer": "HP",
      "Model Name": "15-bs002nv (i3-6006U/4GB/128GB/FHD/W10)",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "Full HD 1920x1080",
      "CPU": "Intel Core i3 6006U 2GHz",
      "RAM": "4GB",
      "Storage": "128GB SSD",
      "GPU": "Intel HD Graphics 520",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "1.91kg",
      "Price": 3903588
    },
    {
      "Manufacturer": "Asus",
      "Model Name": "VivoBook Max",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "1366x768",
      "CPU": "Intel Core i5 7200U 2.5GHz",
      "RAM": "4GB",
      "Storage": "256GB SSD",
      "GPU": "Intel HD Graphics 620",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "2kg",
      "Price": 5212401.48
    },
    {
      "Manufacturer": "MSI",
      "Model Name": "GS73VR 7RG",
      "Category": "Gaming",
      "Screen Size": 17.3,
      "Screen": "Full HD 1920x1080",
      "CPU": "Intel Core i7 7700HQ 2.8GHz",
      "RAM": "16GB",
      "Storage": "256GB SSD +  2TB HDD",
      "GPU": "Nvidia GeForce GTX 1070",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "2.43kg",
      "Price": 21776508
    },
    {
      "Manufacturer": "Asus",
      "Model Name": "X541UA-DM1897 (i3-6006U/4GB/256GB/FHD/Linux)",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "Full HD 1920x1080",
      "CPU": "Intel Core i3 6006U 2GHz",
      "RAM": "4GB",
      "Storage": "256GB SSD",
      "GPU": "Intel HD Graphics 520",
      "Operating System": "Linux",
      "Operating System Version": "",
      "Weight": "2kg",
      "Price": 3690180
    },
    {
      "Manufacturer": "Dell",
      "Model Name": "Inspiron 5770",
      "Category": "Notebook",
      "Screen Size": 17.3,
      "Screen": "Full HD 1920x1080",
      "CPU": "Intel Core i7 8550U 1.8GHz",
      "RAM": "16GB",
      "Storage": "256GB SSD +  2TB HDD",
      "GPU": "AMD Radeon 530",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "2.8kg",
      "Price": 11550708
    },
    {
      "Manufacturer": "Dell",
      "Model Name": "Vostro 5471",
      "Category": "Ultrabook",
      "Screen Size": 14,
      "Screen": "Full HD 1920x1080",
      "CPU": "Intel Core i5 8250U 1.6GHz",
      "RAM": "8GB",
      "Storage": "256GB SSD",
      "GPU": "Intel UHD Graphics 620",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "1.7kg",
      "Price": 7816068
    },
    {
      "Manufacturer": "Lenovo",
      "Model Name": "IdeaPad 520S-14IKB",
      "Category": "Notebook",
      "Screen Size": 14,
      "Screen": "IPS Panel Full HD 1920x1080",
      "CPU": "Intel Core i3 7130U 2.7GHz",
      "RAM": "8GB",
      "Storage": "256GB SSD",
      "GPU": "Intel HD Graphics 620",
      "Operating System": "No OS",
      "Operating System Version": "",
      "Weight": "1.7kg",
      "Price": 5326308
    },
    {
      "Manufacturer": "Asus",
      "Model Name": "UX410UA-GV350T (i5-8250U/8GB/256GB/FHD/W10)",
      "Category": "Notebook",
      "Screen Size": 14,
      "Screen": "Full HD 1920x1080",
      "CPU": "Intel Core i5 8250U 1.6GHz",
      "RAM": "8GB",
      "Storage": "256GB SSD",
      "GPU": "Intel UHD Graphics 620",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "1.4kg",
      "Price": 8367372
    },
    {
      "Manufacturer": "HP",
      "Model Name": "250 G6",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "Full HD 1920x1080",
      "CPU": "Intel Core i5 7200U 2.5GHz",
      "RAM": "8GB",
      "Storage": "256GB SSD",
      "GPU": "Intel HD Graphics 620",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "1.86kg",
      "Price": 6135480
    },
    {
      "Manufacturer": "Asus",
      "Model Name": "ZenBook Pro",
      "Category": "Ultrabook",
      "Screen Size": 15.6,
      "Screen": "Full HD 1920x1080",
      "CPU": "Intel Core i7 7700HQ 2.8GHz",
      "RAM": "16GB",
      "Storage": "512GB SSD",
      "GPU": "Nvidia GeForce GTX 1050 Ti",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "1.8kg",
      "Price": 17632836
    },
    {
      "Manufacturer": "HP",
      "Model Name": "250 G6",
      "Category": "Notebook",
      "Screen Size": 15.6,
      "Screen": "1366x768",
      "CPU": "Intel Core i3 6006U 2GHz",
      "RAM": "4GB",
      "Storage": "500GB HDD",
      "GPU": "AMD Radeon 520",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "1.86kg",
      "Price": 3900831.48
    },
    {
      "Manufacturer": "HP",
      "Model Name": "Stream 14-AX040wm",
      "Category": "Notebook",
      "Screen Size": 14,
      "Screen": "1366x768",
      "CPU": "Intel Celeron Dual Core N3060 1.6GHz",
      "RAM": "4GB",
      "Storage": "32GB SSD",
      "GPU": "Intel HD Graphics 400",
      "Operating System": "Windows",
      "Operating System Version": 10,
      "Weight": "1.44kg",
      "Price": 2036268
    }
  ];