export const columns3 = ["Assessment Title","Entity","Key","Procedure Title","Test Results","Procedure State","Issue Title","Code","Issue State","Recommendation Title","Business Contact","Due Date","Days Overdue","Recommendation Created Date"];
export const data3 = [
    {
      "Assessment Title": "01 - Recomendation Dashboard Assess",
      "Entity": "Corporate",
      "Key": "No",
      "Procedure Title": "Imported Issues",
      "Test Results": "Not Tested",
      "Procedure State": "Not Started",
      "Issue Title": "Issue 01 - RecDashboard",
      "Code": "1",
      "Issue State": "Not Started",
      "Recommendation Title": "Start reviewing access",
      "Audit Staff Area": "IT",
      "Recommendation State": "In Progress@edit",
      "Business Contact": "David Carr",
      "Due Date": 43438,
      "Days Overdue": 1155,
      "Recommendation Created Date": 43398
    },
    {
      "Assessment Title": "01 - Recomendation Dashboard Assess",
      "Entity": "Corporate",
      "Key": "No",
      "Procedure Title": "Imported Issues",
      "Test Results": "Not Tested",
      "Procedure State": "Not Started",
      "Issue Title": "Issue 01 - RecDashboard",
      "Code": "1",
      "Issue State": "Not Started",
      "Recommendation Title": "New01 - Rec",
      "Audit Staff Area": "IT",
      "Recommendation State": "Not Started",
      "Due Date": 44545,
      "Days Overdue": 364,
      "Recommendation Created Date": 43398
    },
    {
      "Assessment Title": "01 - Recomendation Dashboard Assess",
      "Entity": "Corporate",
      "Key": "No",
      "Procedure Title": "Imported Issues",
      "Test Results": "Not Tested",
      "Procedure State": "Not Started",
      "Issue Title": "Issue 01 - RecDashboard",
      "Code": "1",
      "Issue State": "Not Started",
      "Recommendation Title": "New02 - Rec",
      "Audit Staff Area": "IT",
      "Recommendation State": "Not Started",
      "Due Date": 44546,
      "Days Overdue": 363,
      "Recommendation Created Date": 43398
    },
    {
      "Assessment Title": "01 - Recomendation Dashboard Assess",
      "Entity": "Corporate",
      "Key": "No",
      "Procedure Title": "Imported Issues",
      "Test Results": "Not Tested",
      "Procedure State": "Not Started",
      "Issue Title": "Issue 01 - RecDashboard",
      "Code": "1",
      "Issue State": "Not Started",
      "Recommendation Title": "New03",
      "Audit Staff Area": "IT",
      "Recommendation State": "Not Started",
      "Due Date": 44545,
      "Days Overdue": 364,
      "Recommendation Created Date": 43398
    },
    {
      "Assessment Title": "01 - Recomendation Dashboard Assess",
      "Entity": "Corporate",
      "Key": "No",
      "Procedure Title": "Imported Issues",
      "Test Results": "Not Tested",
      "Procedure State": "Not Started",
      "Issue Title": "Issue 01 - RecDashboard",
      "Code": "1",
      "Issue State": "Not Started",
      "Recommendation Title": "New04",
      "Audit Staff Area": "IT",
      "Recommendation State": "Not Started",
      "Due Date": 44561,
      "Days Overdue": 352,
      "Recommendation Created Date": 43398
    },
    {
      "Assessment Title": "01 - Recomendation Dashboard Assess",
      "Entity": "Corporate",
      "Key": "No",
      "Procedure Title": "Imported Issues",
      "Test Results": "Not Tested",
      "Procedure State": "Not Started",
      "Issue Title": "Issue 01 - RecDashboard",
      "Code": "1",
      "Issue State": "Not Started",
      "Recommendation Title": "New05",
      "Audit Staff Area": "IT",
      "Recommendation State": "Not Started",
      "Due Date": 44166,
      "Days Overdue": 635,
      "Recommendation Created Date": 43398
    },
    {
      "Assessment Title": "01 - Recomendation Dashboard Assess",
      "Entity": "Corporate",
      "Key": "No",
      "Procedure Title": "Imported Issues",
      "Test Results": "Not Tested",
      "Procedure State": "Not Started",
      "Issue Title": "Issue 01 - RecDashboard",
      "Code": "1",
      "Issue State": "Not Started",
      "Recommendation Title": "New06",
      "Audit Staff Area": "IT",
      "Recommendation State": "Not Started",
      "Due Date": 44172,
      "Days Overdue": 631,
      "Recommendation Created Date": 43398
    },
    {
      "Assessment Title": "01 - Recomendation Dashboard Assess",
      "Entity": "Corporate",
      "Key": "No",
      "Procedure Title": "Imported Issues",
      "Test Results": "Not Tested",
      "Procedure State": "Not Started",
      "Issue Title": "Issue 01 - RecDashboard",
      "Code": "1",
      "Issue State": "Not Started",
      "Recommendation Title": "New07",
      "Audit Staff Area": "IT",
      "Recommendation State": "Not Started",
      "Due Date": 44181,
      "Days Overdue": 624,
      "Recommendation Created Date": 43398
    },
    {
      "Assessment Title": "01 - Recomendation Dashboard Assess",
      "Entity": "Corporate",
      "Key": "No",
      "Procedure Title": "Imported Issues",
      "Test Results": "Not Tested",
      "Procedure State": "Not Started",
      "Issue Title": "Issue 01 - RecDashboard",
      "Code": "1",
      "Issue State": "Not Started",
      "Recommendation Title": "New08",
      "Audit Staff Area": "IT",
      "Recommendation State": "Not Started",
      "Due Date": 44201,
      "Days Overdue": 610,
      "Recommendation Created Date": 43398
    },
    {
      "Assessment Title": "01 - Recomendation Dashboard Assess",
      "Entity": "Corporate",
      "Key": "No",
      "Procedure Title": "Imported Issues",
      "Test Results": "Not Tested",
      "Procedure State": "Not Started",
      "Issue Title": "Issue 01 - RecDashboard",
      "Code": "1",
      "Issue State": "Not Started",
      "Recommendation Title": "New09",
      "Audit Staff Area": "IT",
      "Recommendation State": "Not Started",
      "Due Date": 44271,
      "Days Overdue": 560,
      "Recommendation Created Date": 43398
    },
    {
      "Assessment Title": "01 - Recomendation Dashboard Assess",
      "Entity": "Corporate",
      "Key": "No",
      "Procedure Title": "Imported Issues",
      "Test Results": "Not Tested",
      "Procedure State": "Not Started",
      "Issue Title": "Issue 01 - RecDashboard",
      "Code": "1",
      "Issue State": "Not Started",
      "Recommendation Title": "New10",
      "Audit Staff Area": "IT",
      "Recommendation State": "Not Started",
      "Due Date": 44292,
      "Days Overdue": 545,
      "Recommendation Created Date": 43398
    },
    {
      "Assessment Title": "01 - Recomendation Dashboard Assess",
      "Entity": "Corporate",
      "Key": "No",
      "Procedure Title": "Imported Issues",
      "Test Results": "Not Tested",
      "Procedure State": "Not Started",
      "Issue Title": "Issue 01 - RecDashboard",
      "Code": "1",
      "Issue State": "Not Started",
      "Recommendation Title": "New11",
      "Audit Staff Area": "IT",
      "Recommendation State": "Not Started",
      "Due Date": 43865,
      "Days Overdue": 850,
      "Recommendation Created Date": 43398
    },
    {
      "Assessment Title": "01 - Recomendation Dashboard Assess",
      "Entity": "Corporate",
      "Key": "No",
      "Procedure Title": "Imported Issues",
      "Test Results": "Not Tested",
      "Procedure State": "Not Started",
      "Issue Title": "Issue 01 - RecDashboard",
      "Code": "1",
      "Issue State": "Not Started",
      "Recommendation Title": "New12",
      "Audit Staff Area": "IT",
      "Recommendation State": "Not Started",
      "Due Date": 44579,
      "Days Overdue": 340,
      "Recommendation Created Date": 43398
    },
    {
      "Assessment Title": "01 - Recomendation Dashboard Assess",
      "Entity": "Corporate",
      "Key": "No",
      "Procedure Title": "Imported Issues",
      "Test Results": "Not Tested",
      "Procedure State": "Not Started",
      "Issue Title": "Issue 01 - RecDashboard",
      "Code": "1",
      "Issue State": "Not Started",
      "Recommendation Title": "New13",
      "Audit Staff Area": "IT",
      "Recommendation State": "Not Started",
      "Due Date": 44580,
      "Days Overdue": 339,
      "Recommendation Created Date": 43398
    },
    {
      "Assessment Title": "01 - Recomendation Dashboard Assess",
      "Entity": "Corporate",
      "Key": "No",
      "Procedure Title": "Imported Issues",
      "Test Results": "Not Tested",
      "Procedure State": "Not Started",
      "Issue Title": "Issue 01 - RecDashboard",
      "Code": "1",
      "Issue State": "Not Started",
      "Recommendation Title": "New14",
      "Audit Staff Area": "Yes",
      "Recommendation State": "Not Started",
      "Due Date": 44572,
      "Days Overdue": 345,
      "Recommendation Created Date": 43398
    },
    {
      "Assessment Title": "01 - Recomendation Dashboard Assess",
      "Entity": "Corporate",
      "Key": "No",
      "Procedure Title": "Imported Issues",
      "Test Results": "Not Tested",
      "Procedure State": "Not Started",
      "Issue Title": "Issue 01 - RecDashboard",
      "Code": "1",
      "Issue State": "Not Started",
      "Recommendation Title": "New15",
      "Audit Staff Area": "Yes",
      "Recommendation State": "Not Started",
      "Due Date": 43482,
      "Days Overdue": 1123,
      "Recommendation Created Date": 43398
    },
    {
      "Assessment Title": "01 - Recomendation Dashboard Assess",
      "Entity": "Corporate",
      "Key": "No",
      "Procedure Title": "Imported Issues",
      "Test Results": "Not Tested",
      "Procedure State": "Not Started",
      "Issue Title": "Issue 01 - RecDashboard",
      "Code": "1",
      "Issue State": "Not Started",
      "Recommendation Title": "New16",
      "Audit Staff Area": "Yes",
      "Recommendation State": "Not Started",
      "Due Date": 43483,
      "Days Overdue": 1122,
      "Recommendation Created Date": 43398
    },
    {
      "Assessment Title": "01 - Recomendation Dashboard Assess",
      "Entity": "Corporate",
      "Key": "No",
      "Procedure Title": "Imported Issues",
      "Test Results": "Not Tested",
      "Procedure State": "Not Started",
      "Issue Title": "Issue 01 - RecDashboard",
      "Code": "1",
      "Issue State": "Not Started",
      "Recommendation Title": "New17",
      "Audit Staff Area": "Yes",
      "Recommendation State": "Not Started",
      "Due Date": 43484,
      "Days Overdue": 1121,
      "Recommendation Created Date": 43398
    },
    {
      "Assessment Title": "01 - Recomendation Dashboard Assess",
      "Entity": "Corporate",
      "Key": "No",
      "Procedure Title": "Imported Issues",
      "Test Results": "Not Tested",
      "Procedure State": "Not Started",
      "Issue Title": "Issue 01 - RecDashboard",
      "Code": "1",
      "Issue State": "Not Started",
      "Recommendation Title": "New18",
      "Audit Staff Area": "Yes",
      "Recommendation State": "Not Started",
      "Due Date": 43485,
      "Days Overdue": 1123,
      "Recommendation Created Date": 43398
    },
    {
      "Assessment Title": "01 - Recomendation Dashboard Assess",
      "Entity": "Corporate",
      "Key": "No",
      "Procedure Title": "Imported Issues",
      "Test Results": "Not Tested",
      "Procedure State": "Not Started",
      "Issue Title": "Issue 01 - RecDashboard",
      "Code": "1",
      "Issue State": "Not Started",
      "Recommendation Title": "New19",
      "Audit Staff Area": "Yes",
      "Recommendation State": "Not Started",
      "Due Date": 43486,
      "Days Overdue": 1121,
      "Recommendation Created Date": 43398
    },
    {
      "Assessment Title": "01 - Recomendation Dashboard Assess",
      "Entity": "Corporate",
      "Key": "No",
      "Procedure Title": "Imported Issues",
      "Test Results": "Not Tested",
      "Procedure State": "Not Started",
      "Issue Title": "Issue 01 - RecDashboard",
      "Code": "1",
      "Issue State": "Not Started",
      "Recommendation Title": "New20",
      "Audit Staff Area": "Yes",
      "Recommendation State": "Not Started",
      "Due Date": 43487,
      "Days Overdue": 1120,
      "Recommendation Created Date": 43398
    },
    {
      "Assessment Title": "01 - Recomendation Dashboard Assess",
      "Entity": "Corporate",
      "Key": "No",
      "Procedure Title": "Imported Issues",
      "Test Results": "Not Tested",
      "Procedure State": "Not Started",
      "Issue Title": "Issue 01 - RecDashboard",
      "Code": "1",
      "Issue State": "Not Started",
      "Recommendation Title": "New21",
      "Audit Staff Area": "Yes",
      "Recommendation State": "Not Started",
      "Due Date": 43488,
      "Days Overdue": 1119,
      "Recommendation Created Date": 43398
    },
    {
      "Assessment Title": "01 - Recomendation Dashboard Assess",
      "Entity": "Corporate",
      "Key": "No",
      "Procedure Title": "Imported Issues",
      "Test Results": "Not Tested",
      "Procedure State": "Not Started",
      "Issue Title": "Issue 01 - RecDashboard",
      "Code": "1",
      "Issue State": "Not Started",
      "Recommendation Title": "New22",
      "Audit Staff Area": "Yes",
      "Recommendation State": "Not Started",
      "Due Date": 43489,
      "Days Overdue": 1118,
      "Recommendation Created Date": 43398
    },
    {
      "Assessment Title": "01 - Recomendation Dashboard Assess",
      "Entity": "Corporate",
      "Key": "No",
      "Procedure Title": "Imported Issues",
      "Test Results": "Not Tested",
      "Procedure State": "Not Started",
      "Issue Title": "Issue 01 - RecDashboard",
      "Code": "1",
      "Issue State": "Not Started",
      "Recommendation Title": "New23",
      "Audit Staff Area": "Yes",
      "Recommendation State": "Not Started",
      "Due Date": 43490,
      "Days Overdue": 1117,
      "Recommendation Created Date": 43398
    }
  ];
